cors:
  originPatterns: http://localhost:8080,http://localhost:3000
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  application:
    name: promotion_app

  datasource:
    url: jdbc:postgresql://localhost:5432/rest_springboot
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false

springdoc:
  paths-to-match:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true
