name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: DockerHub Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build Application JAR
      working-directory: ./
      run: mvn clean package -DskipTests 

    - name: List target directory
      run: ls -la target/

    - name: Docker Cleanup
      run: docker system prune -f

    - name: Docker Compose Build
      working-directory: ./
      run: docker compose build

    - name: Push to DockerHub
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/promotion-app:latest ${{ secrets.DOCKER_USERNAME }}/promotion-app:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/promotion-app:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/promotion-app:latest
